-- 给 games.name_cn 填中文映射（前端展示 + AI 助手都用得到）
UPDATE games SET name_cn = '黑神话：悟空' WHERE name = 'Black Myth: Wukong';
UPDATE games SET name_cn = '赛博朋克2077' WHERE name = 'Cyberpunk 2077';
UPDATE games SET name_cn = '赛博朋克2077 终极版' WHERE name = 'Cyberpunk 2077: Ultimate Edition';
UPDATE games SET name_cn = '艾尔登法环' WHERE name = 'Elden Ring';
UPDATE games SET name_cn = '艾尔登法环：黄金树幽影 DLC' WHERE name = 'Elden Ring: Shadow of the Erdtree';
UPDATE games SET name_cn = '荒野大镖客：救赎2' WHERE name = 'Red Dead Redemption 2';
UPDATE games SET name_cn = '巫师3：狂猎' WHERE name = 'The Witcher 3: Wild Hunt';
UPDATE games SET name_cn = '侠盗猎车手V' WHERE name = 'Grand Theft Auto V';
UPDATE games SET name_cn = '怪物猎人：荒野' WHERE name = 'Monster Hunter Wilds';
UPDATE games SET name_cn = '生化危机：安魂曲' WHERE name = '生化危机:安魂曲';
UPDATE games SET name_cn = '生化危机：安魂曲 豪华版' WHERE name = '生化危机:安魂曲 豪华版';
UPDATE games SET name_cn = '三更' WHERE name = '三更';
UPDATE games SET name_cn = '东方奇缘记' WHERE name = '东方奇缘记';
UPDATE games SET name_cn = '你的另一个老婆' WHERE name = '你的另一个老婆';
UPDATE games SET name_cn = '古墓丽影：暗影' WHERE name = 'Shadow of the Tomb Raider';
UPDATE games SET name_cn = '古墓丽影：崛起' WHERE name = 'Rise of the Tomb Raider';
UPDATE games SET name_cn = '古墓丽影' WHERE name = 'Tomb Raider';
UPDATE games SET name_cn = '地平线：零之曙光' WHERE name = 'Horizon Zero Dawn Complete Edition';
UPDATE games SET name_cn = '地平线：西之绝境' WHERE name = 'Horizon Forbidden West Complete Edition';
UPDATE games SET name_cn = '空洞骑士：丝之歌' WHERE name = 'Hollow Knight: Silksong';
UPDATE games SET name_cn = '空洞骑士' WHERE name = 'Hollow Knight';
UPDATE games SET name_cn = '星露谷物语' WHERE name = 'Stardew Valley';
UPDATE games SET name_cn = '泰拉瑞亚' WHERE name = 'Terraria';
UPDATE games SET name_cn = '饥荒联机版' WHERE name = "Don't Starve Together";
UPDATE games SET name_cn = '毁灭永恒' WHERE name = 'DOOM Eternal';
UPDATE games SET name_cn = '控制' WHERE name = 'Control';
UPDATE games SET name_cn = '死亡搁浅' WHERE name = 'Death Stranding';
UPDATE games SET name_cn = '刺客信条：瓦尔哈拉' WHERE name = "Assassin's Creed Valhalla";
UPDATE games SET name_cn = '刺客信条：奥德赛' WHERE name = "Assassin's Creed Odyssey";
UPDATE games SET name_cn = '刺客信条：起源' WHERE name = "Assassin's Creed Origins";
UPDATE games SET name_cn = '孤岛惊魂6' WHERE name = 'Far Cry 6';
UPDATE games SET name_cn = '孤岛惊魂5' WHERE name = 'Far Cry 5';
UPDATE games SET name_cn = '杀手3' WHERE name = 'Hitman 3';
UPDATE games SET name_cn = '杀手2' WHERE name = 'HITMAN 2';
UPDATE games SET name_cn = '杀手：暗杀世界' WHERE name = 'Hitman: World of Assassination';
UPDATE games SET name_cn = '中土世界：战争之影' WHERE name = 'Middle-earth: Shadow of War';
UPDATE games SET name_cn = '中土世界：魔多之影' WHERE name = 'Middle-earth: Shadow of Mordor';
UPDATE games SET name_cn = '蝙蝠侠：阿卡姆骑士' WHERE name = 'Batman: Arkham Knight';
UPDATE games SET name_cn = '不义联盟2' WHERE name = 'Injustice 2';
UPDATE games SET name_cn = '真人快打11' WHERE name = 'Mortal Kombat 11';
UPDATE games SET name_cn = '铁拳7' WHERE name = 'Tekken 7';
UPDATE games SET name_cn = '街头霸王5' WHERE name = 'Street Fighter 5';
UPDATE games SET name_cn = '街头霸王6' WHERE name = 'Street Fighter 6';
UPDATE games SET name_cn = '鬼泣5' WHERE name = 'Devil May Cry 5';
UPDATE games SET name_cn = '匹诺曹的谎言' WHERE name = "Lies of P";
UPDATE games SET name_cn = '卧龙：苍天陨落' WHERE name = 'Wo Long: Fallen Dynasty';
UPDATE games SET name_cn = '仁王' WHERE name = 'Nioh';
UPDATE games SET name_cn = '死亡细胞' WHERE name = 'Dead Cells';
UPDATE games SET name_cn = '穹顶守护者' WHERE name = 'Dome Keeper';
UPDATE games SET name_cn = '环世界' WHERE name = 'RimWorld';
UPDATE games SET name_cn = '异星工厂' WHERE name = 'Factorio';
UPDATE games SET name_cn = 'Hades II' WHERE name = 'Hades II';
UPDATE games SET name_cn = '哈迪斯' WHERE name = 'Hades';
UPDATE games SET name_cn = '漫威蜘蛛侠2' WHERE name = 'Marvel\'s Spider-Man 2';
UPDATE games SET name_cn = '暗喻幻想 ReFantazio' WHERE name = 'Metaphor: ReFantazio';
UPDATE games SET name_cn = '如龙：无限财富' WHERE name = 'Like a Dragon: Infinite Wealth';
UPDATE games SET name_cn = '如龙7外传：无名之龙' WHERE name = 'Like a Dragon: Gaiden - The Man Who Erased His Name';
UPDATE games SET name_cn = '最后生还者 Part I' WHERE name = 'The Last of Us Part I';
UPDATE games SET name_cn = '战神' WHERE name = 'God of War';
UPDATE games SET name_cn = '战神：诸神黄昏' WHERE name = 'God of War Ragnarok';
UPDATE games SET name_cn = '死亡循环' WHERE name = 'Deathloop';
UPDATE games SET name_cn = '幽灵线：东京' WHERE name = 'Ghostwire: Tokyo';
UPDATE games SET name_cn = '完美音浪' WHERE name = 'Hi-Fi RUSH';
UPDATE games SET name_cn = '采石场' WHERE name = 'The Quarry';
UPDATE games SET name_cn = '直到黎明' WHERE name = 'Until Dawn';
UPDATE games SET name_cn = '底特律：成为人类' WHERE name = 'Detroit: Become Human';
UPDATE games SET name_cn = '异星探险家' WHERE name = 'Astroneer';
UPDATE games SET name_cn = '无人深空' WHERE name = "No Man's Sky";
UPDATE games SET name_cn = '坎巴拉太空计划2' WHERE name = 'Kerbal Space Program 2';
UPDATE games SET name_cn = '寒霜朋克' WHERE name = 'Frostpunk';
UPDATE games SET name_cn = '寒霜朋克2' WHERE name = 'Frostpunk 2';
UPDATE games SET name_cn = '这是我的战争' WHERE name = 'This War of Mine';
UPDATE games SET name_cn = '莫塔守山人' WHERE name = 'Children of Morta';
UPDATE games SET name_cn = '恐鬼症' WHERE name = 'Phasmophobia';
UPDATE games SET name_cn = '致命公司' WHERE name = 'Lethal Company';
UPDATE games SET name_cn = '背包英雄' WHERE name = 'Backpack Hero';
UPDATE games SET name_cn = '杀戮尖塔' WHERE name = 'Slay the Spire';
UPDATE games SET name_cn = '博德之门3' WHERE name = "Baldurs Gate 3";
UPDATE games SET name_cn = '博德之门3 数字豪华版' WHERE name = "Baldur's Gate 3 Digital Deluxe Edition";
UPDATE games SET name_cn = 'A Way Out 逃出生天' WHERE name = 'A Way Out';
UPDATE games SET name_cn = 'Frostpunk 2 寒霜朋克2' WHERE name = 'Frostpunk 2';
UPDATE games SET name_cn = 'Fullbright 全英展' WHERE name = 'Fullbright Pres';
UPDATE games SET name_cn = 'RollBot 机器人之路' WHERE name = 'RollBot';
UPDATE games SET name_cn = '神经鹅' WHERE name = '神经鹅';
UPDATE games SET name_cn = '银河守卫战' WHERE name = '银河守卫战';
UPDATE games SET name_cn = '高球王者' WHERE name = '高球王者';
UPDATE games SET name_cn = '剑与魔法的女主角们2' WHERE name = '剑与魔法的女主角们2';
UPDATE games SET name_cn = '我与她们的大学画像' WHERE name = '我与她们的大学画像';
UPDATE games SET name_cn = '永恒边境' WHERE name = 'Borderlands 3';
UPDATE games SET name_cn = '辐射4' WHERE name = 'Fallout 4';
UPDATE games SET name_cn = '星空' WHERE name = 'Starfield';
UPDATE games SET name_cn = 'PUBG 绝地求生' WHERE name = 'PUBG: BATTLEGROUNDS';
UPDATE games SET name_cn = '战地2042' WHERE name = 'Battlefield 2042';
UPDATE games SET name_cn = '模拟人生4' WHERE name = 'The Sims 4';
UPDATE games SET name_cn = '城市天际线2' WHERE name = 'Cities: Skylines II';
UPDATE games SET name_cn = '城市天际线' WHERE name = 'Cities: Skylines';
UPDATE games SET name_cn = '足球经理2024' WHERE name = 'Football Manager 2024';
UPDATE games SET name_cn = '帝国时代4' WHERE name = 'Age of Empires IV';
UPDATE games SET name_cn = '帝国时代2终极版' WHERE name = 'Age of Empires II: Definitive Edition';
UPDATE games SET name_cn = '全面战争：战锤3' WHERE name = 'Total War: Warhammer III';
UPDATE games SET name_cn = '群星' WHERE name = 'Stellaris';
UPDATE games SET name_cn = '钢铁雄心4' WHERE name = 'Hearts of Iron IV';
UPDATE games SET name_cn = '十字军之王3' WHERE name = 'Crusader Kings III';
UPDATE games SET name_cn = '维多利亚3' WHERE name = 'Victoria 3';
UPDATE games SET name_cn = '欧陆风云4' WHERE name = 'Europa Universalis IV';
UPDATE games SET name_cn = '骑砍2：领主' WHERE name = 'Mount & Blade II: Bannerlord';
UPDATE games SET name_cn = '永劫无间' WHERE name = 'Naraka: Bladepoint';
UPDATE games SET name_cn = '英雄传说：黎之轨迹' WHERE name = 'The Legend of Heroes: Trails Through Daybreak';
UPDATE games SET name_cn = '幽灵行动：断点' WHERE name = "Tomp Clancy's Ghost Recon Breakpoint";
UPDATE games SET name_cn = '看门狗：军团' WHERE name = 'Watch Dogs: Legion';
UPDATE games SET name_cn = '正当防卫4' WHERE name = 'Just Cause 4';
UPDATE games SET name_cn = '彩虹六号：围攻' WHERE name = 'Rainbow Six Siege';
UPDATE games SET name_cn = '全境封锁2' WHERE name = "Tom Clancy's The Division 2";
UPDATE games SET name_cn = '命运2：光陨之秋' WHERE name = 'Destiny 2: Lightfall';
UPDATE games SET name_cn = '战争雷霆' WHERE name = 'War Thunder';
UPDATE games SET name_cn = '坦克世界' WHERE name = 'World of Tanks';
UPDATE games SET name_cn = '武装突袭3' WHERE name = 'Arma 3';
UPDATE games SET name_cn = '战术小队' WHERE name = 'Squad';
UPDATE games SET name_cn = '叛乱：沙漠风暴' WHERE name = 'Insurgency: Sandstorm';
UPDATE games SET name_cn = '严阵以待' WHERE name = 'Ready or Not';
UPDATE games SET name_cn = '收获日3' WHERE name = 'Payday 3';
UPDATE games SET name_cn = '收获日2' WHERE name = 'Payday 2';
UPDATE games SET name_cn = '求生之路2' WHERE name = 'Left 4 Dead 2';
UPDATE games SET name_cn = '命运永恒' WHERE name = 'DOOM Eternal';
UPDATE games SET name_cn = '地平线：西之绝境 完整版' WHERE name = 'Horizon Forbidden West Complete Edition';
UPDATE games SET name_cn = '仁王' WHERE name = 'Nier Replicant ver.1.22';
UPDATE games SET name_cn = '尼尔：机械纪元' WHERE name = 'NieR: Automata';
UPDATE games SET name_cn = '女神异闻录4 黄金版' WHERE name = 'Persona 4 Golden';
UPDATE games SET name_cn = '女神异闻录5 皇家版' WHERE name = 'Persona 5 Royal';
UPDATE games SET name_cn = '掠食' WHERE name = 'Prey';
UPDATE games SET name_cn = '八方旅人2' WHERE name = 'Octopath Traveler II';
UPDATE games SET name_cn = '对马岛之魂' WHERE name = 'Ghost of Tsushima';
UPDATE games SET name_cn = '死亡搁浅 导演剪辑版' WHERE name = "Death Stranding Director's Cut";
UPDATE games SET name_cn = '赛博朋克2077 往日之影 DLC' WHERE name = 'Cyberpunk 2077: Phantom Liberty';
UPDATE games SET name_cn = 'EA SPORTS FC 25' WHERE name = 'EA SPORTS FC 25';
UPDATE games SET name_cn = 'EA SPORTS FC 24' WHERE name = 'EA SPORTS FC 24';
UPDATE games SET name_cn = 'GTA 三部曲终极版' WHERE name = 'GTA Trilogy Definitive Edition';
UPDATE games SET name_cn = '怪物猎人：世界' WHERE name = 'Monster Hunter: World';
UPDATE games SET name_cn = '怪物猎人：崛起' WHERE name = 'Monster Hunter Rise';
UPDATE games SET name_cn = '生化危机4 重制版' WHERE name = 'Resident Evil 4 Remake';
UPDATE games SET name_cn = '生化危机：村庄' WHERE name = 'Resident Evil Village';
UPDATE games SET name_cn = '寂静岭2 重制版' WHERE name = 'Silent Hill 2 Remake';
